DurbanJuly/DurbanJuly.Mvc.Ui/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using DurbanJuly.Domain;
using DurbanJuly.Domain.Services;
using DurbanJuly.Models;
using DurbanJuly.Mvc.Ui.Controllers.Base;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DurbanJuly.Mvc.Ui.Controllers
{
    public class EventController : BaseController
    {

        private readonly EventService _eventService;
        private readonly IMapper _mapper;
        public EventController(EventService eventService, IMapper mapper)
        {
            _eventService = eventService;
            _mapper = mapper;
        }
        // GET: EventController
        public ActionResult Index(long id)
        {
            var model = _eventService.GetEvents(id);
            ViewBag.Id = id;
            return View(model);
        }

        // GET: EventController/Create
        public ActionResult Create(int id)
        {
            
            var model = new EventModel
            {
                TournamentId = id
            };

            return View(model);
        }

        // POST: EventController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EventModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _mapper.Map<Event>(model);
                result.Id = 0;
                result.Tournament = null;
                await _eventService.InsertAsync(result);
                return RedirectToAction("Index", new { id = model.TournamentId});
            }
            return View(model);
        }

        // GET: EventController/Edit/5
        public ActionResult Edit(int id)
        {
            var eventD = _eventService.Get().FirstOrDefault(x => x.Id == id);
            var model = _mapper.Map<EventModel>(eventD);
            return View(model);
        }

        // POST: EventController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EventModel model)
        {
            if (ModelState.IsValid)
            {
                await _eventService.UpdateEventAsync(model);
                return RedirectToAction("Index", new { id = model.TournamentId });
            }

            return View();
        }

        // GET: EventController/Delete/5
        public ActionResult Delete(int id)
        {
            var tournament = _eventService.Get().FirstOrDefault(x => x.Id == id);
            var model = _mapper.Map<EventModel>(tournament);
            return View(model);
        }

        // POST: EventController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(EventModel model)
        {
            await _eventService.DeleteEvent(model.Id);
            return RedirectToAction("Index", new { id = model.TournamentId });
        }
    }
}

DurbanJuly/DurbanJuly.Mvc.Ui/Controllers/EventDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using DurbanJuly.Models;
using DurbanJuly.Mvc.Ui.Controllers.Base;

namespace DurbanJuly.Mvc.Ui.Controllers
{
    public class EventDetailController : BaseController
    {
        private readonly Domain.Services.EventDetailService _eventDetailService;
        private readonly IMapper _mapper;
        public EventDetailController(Domain.Services.EventDetailService eventDetailService, IMapper mapper)
        {
            _eventDetailService = eventDetailService;
            _mapper = mapper;
        }
        public ActionResult Index(long id)
        {
            var model = _eventDetailService.GetEventDetails(id);
            ViewBag.Id = id;
            return View(model);
        }

        // GET: EventDetailController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EventDetailController/Create
        public ActionResult Create(int id)
        {
            var statuses = _eventDetailService.GetEventStatuses().Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            var model = new EventDetailModel
            {
                EventId = id,
                Statuses = statuses
            };

            return View(model);
        }


        // POST: EventDetailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventDetailModel model)
        {

            if (ModelState.IsValid)
            {
                var result = _mapper.Map<Domain.EventDetail>(model);
                _eventDetailService.SaveEventDetails(result);
                return RedirectToAction("Index", new { id = model.EventId });
            }
            var statuses = _eventDetailService.GetEventStatuses().Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            model.Statuses = statuses;
            return View(model);
        }

        // GET: EventDetailController/Edit/5
        public ActionResult Edit(int id)
        {
            var eventD = _eventDetailService.Get().FirstOrDefault(x => x.Id == id);
            var statuses = _eventDetailService.GetEventStatuses().Select(x => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem { Value = x.Id.ToString(), Text = x.Name }).ToList();
            var model = _mapper.Map<EventDetailModel>(eventD);
            model.Statuses = statuses;
            return View(model);
        }

        // POST: EventDetailController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EventDetailModel model)
        {
            if (ModelState.IsValid)
            {
                await _eventDetailService.UpdateEventAsync(model);
                return RedirectToAction("Index", new { id = model.EventId });
            }

            return View(model);
        }

        // GET: EventDetailController/Delete/5
        public ActionResult Delete(int id)
        {
            var eventD = _eventDetailService.Get().FirstOrDefault(x => x.Id == id);
            var model = _mapper.Map<EventDetailModel>(eventD);
            return View(model);
        }

        // POST: EventDetailController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(EventDetailModel model)
        {
            await _eventDetailService.DeleteEventDetail(model.Id);
            return RedirectToAction("Index", new { id = model.EventId });
        }
    }
}

DurbanJuly/DurbanJuly.Mvc.Ui/Views/Event/Create.cshtml
@model DurbanJuly.Models.EventModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header text-center">
                <strong>Create a new Event</strong>
            </div>
            <div class="card-body">
                <form asp-action="Create">
                    <input asp-for="TournamentId" class="form-control" type="hidden" />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Number" class="control-label"></label>
                        <input asp-for="Number" class="form-control" />
                        <span asp-validation-for="Number" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventDateTime" class="control-label"></label>
                        <input asp-for="EventDateTime" class="form-control" />
                        <span asp-validation-for="EventDateTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventEndDateTime" class="control-label"></label>
                        <input asp-for="EventEndDateTime" class="form-control" />
                        <span asp-validation-for="EventEndDateTime" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="AutoClose" /> @Html.DisplayNameFor(model => model.AutoClose)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
                <div>
                    <a asp-action="Index" asp-route-id="@Model?.TournamentId">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>

DurbanJuly/DurbanJuly.Mvc.Ui/Views/Event/Delete.cshtml
@model DurbanJuly.Models.EventModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div>
    <hr />
    <dl class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header text-center">
                    <strong>Are you sure you want to delete this event?</strong>
                </div>
                <div class="card-body">
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Number)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.Number)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.EventDateTime)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.EventDateTime)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.EventEndDateTime)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.EventEndDateTime)
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.AutoClose)
                    </dt>
                    <dd class="col-sm-6">
                        @Html.DisplayFor(model => model.AutoClose)
                    </dd>
                    <form asp-action="Delete">
                        <input asp-for="Id" type="hidden">
                        <input type="submit" value="Delete" class="btn btn-danger" /> |
                        <a asp-action="Index" asp-route-id="@Model.TournamentId">Back to List</a>
                    </form>
                    </div>
                </div>
            </div>
</dl>
    

</div>

DurbanJuly/DurbanJuly.Mvc.Ui/Views/Event/Edit.cshtml
@model DurbanJuly.Models.EventModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<hr />
<div class="row">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-header text-center">
                <strong>Edit Event</strong>
            </div>
            <div class="card-body">
                <form asp-action="Edit">
                    <input asp-for="TournamentId" class="form-control" type="hidden" />
                    <input asp-for="Id" type="hidden">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Number" class="control-label"></label>
                        <input asp-for="Number" class="form-control" />
                        <span asp-validation-for="Number" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventDateTime" class="control-label"></label>
                        <input asp-for="EventDateTime" class="form-control" />
                        <span asp-validation-for="EventDateTime" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EventEndDateTime" class="control-label"></label>
                        <input asp-for="EventEndDateTime" class="form-control" />
                        <span asp-validation-for="EventEndDateTime" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="AutoClose" /> @Html.DisplayNameFor(model => model.AutoClose)
                        </label>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
                <div>
                    <a asp-action="Index" asp-route-id="@Model.TournamentId">Back to List</a>
                </div>
            </div>
        </div>
        </div>
    </div>

     

DurbanJuly/DurbanJuly.Mvc.Ui/Views/Event/Index.cshtml
@model IEnumerable<DurbanJuly.Models.EventModel>

@{
    ViewData["Title"] = "View";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>@Model.FirstOrDefault()?.TournamentName Events</h1>

<p class="text-right">
    <a asp-action="Create" class=" btn btn-success"  asp-route-id="@ViewBag.Id">Create New</a>
</p>
<table class="table table-dark">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EventEndDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AutoClose)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventDateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventEndDateTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AutoClose)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                    @Html.ActionLink("View Event Details", "Index", "EventDetail", new { id = item.Id }, new { @class = "btn btn-info" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>